name: scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: "0 5 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  call:
    uses: smigolsmigol/.github/.github/workflows/scorecard.yml@main
